# https://taskfile.dev

version: "3"

tasks:
  install-deps:
    sources:
      - requirements.txt
    cmds:
      - >
        python3 -m pip install
        --break-system-packages
        -r requirements.txt
  build:
    deps:
      - install-deps
    sources:
      - templates/*.j2
      - data.yaml
    generates:
      - public
    cmds:
      - mkdir -p public
      - python3 generate.py

  default:
    - task: build
